=== Raistlin97/demo-projects/trunk/Converters/tools4csv/tools4csv-xbeans/src/main/resources/csv-configuration.cfg.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" >
	
	<xs:simpleType name="converterType" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="csv-to-csv" />
			<xs:enumeration value="csv-to-db" />
			<xs:enumeration value="csv-to-xls" />
			<xs:enumeration value="csv-to-pojo" />
			<xs:enumeration value="db-to-csv" />
			<xs:enumeration value="xml-to-csv" />
			<xs:enumeration value="csv-to-xml" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="dataType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="char" />
			<xs:enumeration value="byte" />
			<xs:enumeration value="int" />
			<xs:enumeration value="integer" />
			<xs:enumeration value="long" />
			<xs:enumeration value="float" />
			<xs:enumeration value="double" />
			<xs:enumeration value="string" />
			<xs:enumeration value="number" />
			<xs:enumeration value="date" />
			<xs:enumeration value="bigint" />
			<xs:enumeration value="biginteger" />
			<xs:enumeration value="bigdecimal" />
		</xs:restriction>
	</xs:simpleType>
	
	
	<xs:element name="csv-configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="parsers" maxOccurs="1" minOccurs="0" />
				<xs:element ref="converters" maxOccurs="1" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="parsers">
		<xs:complexType />
	</xs:element>
	<xs:element name="converters">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="converter"
					minOccurs="1" />
			</xs:sequence>
			<xs:attribute name="parallel" use="required" type="xs:boolean" />
			<xs:attribute name="exitOnError" use="required" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
	<xs:element name="converter" >
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="source" />
				<xs:element ref="target" />
			</xs:sequence>
			<xs:attribute name="active" use="required" type="xs:boolean"/>
			<xs:attribute name="id" use="required" type="xs:string" />
			<xs:attribute name="mkdirs" type="xs:boolean" />
			<xs:attribute name="order" use="required" type="xs:integer" />
			<xs:attribute name="overwrite" type="xs:boolean" />
			<xs:attribute name="sourcePath" use="required" type="xs:string"/>
			<xs:attribute name="targetPath" type="xs:string"/>
			<xs:attribute name="type" use="required" type="converterType" />
		</xs:complexType>
	</xs:element>
	<xs:element name="source">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="select" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="file" use="required" type="xs:string" />
			<xs:attribute name="hasHeader" type="xs:boolean" />
			<xs:attribute name="separator" use="required" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="target">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="collect" minOccurs="0" maxOccurs="1" />
				<xs:element ref="write" minOccurs="0" maxOccurs="1" />
			</xs:sequence>
			<xs:attribute name="file" type="xs:string"/>
			<xs:attribute name="hasHeader" type="xs:boolean" />
			<xs:attribute name="insert" type="xs:boolean" />
			<xs:attribute name="separator" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="collect">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="property" />
			</xs:sequence>
			<xs:attribute name="targetClassName" use="required"
				type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="property" >
		<xs:complexType>
			<xs:attribute name="default" type="xs:string"/>
			<xs:attribute name="format" type="xs:boolean" />
			<xs:attribute name="map-to" use="required" type="xs:string" />
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="pattern" type="xs:string"/>
			<xs:attribute name="type" use="required" type="dataType" />
			<xs:attribute name="index" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="write">
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="connection" />
					<xs:element maxOccurs="unbounded" ref="sql" />
				</xs:sequence>
				<xs:element maxOccurs="unbounded" ref="column" />
			</xs:choice>
			<xs:attribute name="batchSize" use="required" type="xs:integer" />
			<xs:attribute name="from" use="required" type="xs:integer" />
			<xs:attribute name="to" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="connection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="url" />
				<xs:element ref="driverClass" />
				<xs:element ref="userName" />
				<xs:element ref="password" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="url" type="xs:string" />
	<xs:element name="driverClass" type="xs:string" />
	<xs:element name="userName" type="xs:string" />
	<xs:element name="password" type="xs:string" />
	<xs:element name="sql">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="query" />
				<xs:element ref="select" />
			</xs:sequence>
			<xs:attribute name="index" use="required" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="query">
		<xs:complexType mixed="true">
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="namedParam" use="required" type="xs:boolean" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="select">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="column" />
			</xs:sequence>
			<xs:attribute name="batchSize" type="xs:integer" />
			<xs:attribute name="from" type="xs:integer" />
			<xs:attribute name="to" type="xs:integer" />
		</xs:complexType>
	</xs:element>
	<xs:element name="column">
		<xs:complexType>
			<xs:attribute name="default" type="xs:string"/>
			<xs:attribute name="format" type="xs:boolean" />
			<xs:attribute name="header" type="xs:string" />
			<xs:attribute name="index" use="required" type="xs:integer" />
			<xs:attribute name="name" use="required" type="xs:string" />
			<xs:attribute name="pattern" type="xs:string"/>
			<xs:attribute name="type" type="dataType" />
			<xs:attribute name="useQuote" use="required" type="xs:boolean" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Raistlin97/demo-projects/trunk/Converters/tools4csv/tools4csv-xbeans/src/test/resources/csv-config-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<csv-configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../main/xsd/csv-configuration.cfg.xsd">
	
	<converters exitOnError="true" parallel="false">
	
		<converter order="1" type="csv-to-merged" 
			sourcePath="/home/sabuj/temp/in" active="true" id="csv-to-merged"
			targetPath="/home/sabuj/temp/out"
			mkdirs="true" overwrite="true">
			
			<source file="in.csv" separator=","  hasHeader="true">
				<select from="-1" to="-1" batchSize="10">
					<column index="0" name="a0" useQuote="false"/>
					<column index="1" name="a1" useQuote="false"/>
					<column index="2" name="a2" useQuote="false"/>
					<column index="3" name="a3" useQuote="false"/>
					<column index="5" name="a5" useQuote="false"/>
					<column index="7" name="a7" useQuote="false" pattern="dd/MM/yyyyy"/>
				</select>
			</source>
			
			<target >
				<collect id="C" targetClassName="a.b.C" orderBy="b">
					<property map-to="a1" name="a" type="string" default="--" />
					<property map-to="a3" name="b" type="string"/>
				</collect>
				
				<collect id="D" targetClassName="a.b.D">
					<property map-to="a2" name="d" type="string"/>
					<property map-to="a5" name="e" type="string"/>
				</collect>
				
				<write id="write-to-file-1" type="csvWriter" fileName="out1.csv" separator="\t" batchSize="10" from="-1" to="-1">
					<column useQuote="true" name="a1" index="0" type="string"/>
					<column useQuote="true" name="a7" index="1" type="date" format="true" pattern="MM-ddd-yy"/>
				</write>
				
				<write id="write-to-file-2" type="csvWriter" fileName="out2.csv" separator=",">
					<column useQuote="true" name="a4" index="0" type="string"/>
					<column useQuote="true" name="a7" index="1" type="date" format="true" pattern="MMM-ddd-yy"/>
				</write>
				
				<write id="insert-to-db-1" type="databaseWriter">
					<connection>
						<url>sdfasdf</url>
						<driverClass>a.B</driverClass>
						<userName>dsfsf</userName>
						<password>fsdfgsdfg</password>
					</connection>
					<sql index="0">
						<query namedParam="false">
						<![CDATA[
							insert into ...
						]]>
						</query>
						<select >
							<column useQuote="true" name="a3" index="0"/>
							<column useQuote="true" name="a5" index="1"/>
						</select>
					</sql>
					<sql index="1">
						<query namedParam="false">
						<![CDATA[
							insert into ...
						]]>
						</query>
						<select >
							<column useQuote="true" name="a1" index="0"/>
							<column useQuote="true" name="a4" index="1"/>
						</select>
					</sql>
				</write>
				
				
			</target>
		
		</converter>
	</converters>
	
</csv-configuration>
